version = 0.1

[default]
[default.global.parameters]
stack_name = "s3-notification-system"


[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "s3-notification-system"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" EmailAddress=\"nictech23@gmail.com\""
image_repositories = []
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3-notification-system-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dev"
s3_prefix = "s3-notification-system-dev"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev EmailAddress=dev-notifications@example.com"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-notification-system-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-prod"
s3_prefix = "s3-notification-system-prod"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod EmailAddress=nictech23@gmail.com"